### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by pudding126** [haoyanbin918/Group-Contextualization#3]
Could you please release the pre-trained weights of the Diving48 dataset? Thanks.

**Comment by haoyanbin918** [comment]
Please see the following urls:
https://drive.google.com/file/d/1R5jjvbXVZywxTO3NeoDKHiRU9o5NwFrl/view?usp=sharing (TSN-GC-R50 with 16 frames )
and
https://drive.google.com/file/d/14ruza2xqYUDWs5fLewYp1Tz1a9MXj1rV/view?usp=sharing  (TSM-GC-R50 with 16 frames ). Thank you!

**Comment by haoyanbin918** [comment]
Also, the TDN-GC-R50 with 16 frames.
https://drive.google.com/file/d/1sPLV9-XdYMMxHMLd8PGP5anpYtkWq4ar/view?usp=sharing

**Comment by pudding126** [comment]
Hi, thanks for providing the pre-trained models. I try to test the pre-trained GC-TDN model on diving48 dataset, but I get Prec@1 83.161 Prec@5 98.295. Like TDN I only use the center crop to test. Could you please tell me about your test settings? I'm not sure what influenced the results.

**Comment by haoyanbin918** [comment]
> Hi, thanks for providing the pre-trained models. I try to test the pre-trained GC-TDN model on diving48 dataset, but I get Prec@1 83.161 Prec@5 98.295. Like TDN I only use the center crop to test. Could you please tell me about your test settings? I'm not sure what influenced the results.

Sorry for this. I check the checkpoint and find I may share the wrong one. Please see the new one (https://drive.google.com/file/d/12VgcEEP1HgODZYe2dlSpho6wyv-oYmll/view?usp=sharing) and the one of epoch-31 (https://drive.google.com/file/d/1A5pzN8vNduawbJM8b_7o-izcpWUrd97C/view?usp=sharing). 
It is yes we use the center crop with 1 clip to do evaluation. If you have any questions, please directly contact us here or by email: haoyanbin@hotmail.com.

**Comment by pudding126** [comment]
I get the right result, thank you very much!
